sudo: false
dist: trusty
language: rust
rust:
- stable
- beta
- nightly
addons:
  apt:
    packages:
    - libxml2-dev
    - libxslt1-dev
after_success: "./scripts/doc-upload.sh"
env:
  global:
  - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
  - secure: FxgazbjsmCg2KUgenH7Sv+dAsGPXPAeLRHjwI+mybF+bK7u6TMlWa72E6gt6Gz4t36af5LVJQ0O5fmLIdmkQYkGjLLzokzKrkb6GE81N0XZ2tTVV4lMRUS4LoJupyF9n9PhXiPV7e42VWPLVUfxeX76iljsQJQkLwCwH4XL6cTb4ARRciiLZ8EncITYz4kjODf2K7u6/Z7nVVYVaCIQTPaN/wfV4Mz1U4rtqpuXHRHAzurDIbXIDYN0cEcqgWfSpG0sJmbpzwwEp+VWydBETkUemBYoTmTrgi3sN9kp8Yqa/WumGSwLAN0STTtWFw6dNYeZBQ+wZJVxUdBAE+qqUiIfHzykcgvBsxPtV+gGGgvjTo+mN7oCjoYiI92K9sbqzVHBAc/9krEi91qkcz66e1unZg2DjXqpIIvf7QRBndJzKdv5TBJil+dmEPGwdXAbkEPBAOcDDnIeFdhE4cKWI2p0ciOWn1Fz8Pny7JxERVVXRyvwG2D+MdgLe4yPAqe5RL6DsfPrh42ap8NCL9Yu/BQIYI2sHJbVqU3O4FeF7wdjJlLDkEHlP2hmD9XusEixL7ksIARiYciqflE46frU4BoyPxGUulbTS3et6ro0haDJVFcO9Im/4m8gwCfs1HC6y4NmjAuuG0TCn/+SS8jFFowMulbthXpH3v29+LJwNrn4=
